[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "opecore"
version = "0.1.0"
description = "Open Plant Engineering Core - Versioned Object Storage Engine"
authors = [
    { name="Your Name" }
]
dependencies = []
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
